### ISSUE TITLE
Can't install magicl with extensions possible to make your code run on magicl/core functions only?

### ISSUE THREAD

**Issue by AlexanderSimWS** [DurhamSmith/small#1]
Can't install magicl with extensions possible to make your code run on magicl/core functions only?

**Comment by DurhamSmith** [comment]
I can look into this. What is the reason you can use extensions?

**Comment by AlexanderSimWS** [comment]
@DurhamSmith Ok so I managed to install magicI without expokit. The problem was with lapack but by quitting and restarting my repl several times and entering "(asdf:require-system "magicl")", I managed to install it. You don't use expokit in the code right?

**Comment by DurhamSmith** [comment]
@AlexanderSimWS great that you got it to work. I will look into simplifying and documenting the build process soon. 

I did not use expokit so you should be fine. What OS are you using?

Out of curiosity, and if you don't mind sharing, what are you intending to use small for?

**Comment by AlexanderSimWS** [comment]
Sounds great! The videos are good but I'm still trying to understand the source code to be honest. 

Okay good. I'm using MacOS 12.4.

I was looking into ways to represent and simulate DNA nanohydrogels. This would help in designing them. Basically they're short sequences (around 20bp) of single stranded DNA that self-assemble into a molecule that can encapsulate cargo. Now with Nupack and oxDNA we can simulate the strands themselves. But often they're modified to include other things such as disulfide linkages or polymers which can't be simulated with oxDNA. More details are in this paper: https://pubs.acs.org/doi/10.1021/ja512293f 

I read your paper and watched the video playlist and was thinking of writing extensions that would:
1. Design proposed sequences for the nanohydrogels
2. Help screen designs for self-folding
3. Simulate DNA + polymers/other functional groups in LAMMPS

Although for the 3rd extension, I'm not sure how exactly oxDNA is implemented in LAMMPS so I'm not sure whether it's possible in the first place. Any ideas?

**Comment by DurhamSmith** [comment]
Thanks! I'm sure number 3 would be possible and probably not to challenging, although I am not to familiar with LAMMPS so I can't offer any advice off the top of my head. I'll mark this as closed for now but if you need help on any specific issues or questions feel free to reach out by opening up another issue or via email.
